// test_persist.cpp — Rule persistence unit tests (task 11.6)
//
// Validates property 1: Rule persistence round-trip property
//   ∀ ruleset: parse(format(ruleset)) == ruleset
//
// Also covers: save/load basic functionality, noflush mode, syntax error handling, async write

#include "winiptables/persist.hpp"
#include "winiptables/rule_store.hpp"
#include "winiptables/model.hpp"
#include "winiptables/imatch.hpp"  // Full IMatch definition needed for Rule destructor

#include <gtest/gtest.h>

#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>

using namespace winiptables;
namespace fs = std::filesystem;

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

// Temporary file RAII wrapper
struct TempFile {
    std::string path;
    explicit TempFile(const std::string& suffix = "v4") {
        auto tmp = fs::temp_directory_path() / ("winiptables_test_" + suffix);
        path = tmp.string();
    }
    ~TempFile() {
        std::error_code ec;
        fs::remove(path, ec);
    }
};

// Build a simple rule
static Rule make_rule(Target::Kind kind = Target::Kind::kAccept) {
    Rule r;
    r.target.kind = kind;
    return r;
}

// Build a JUMP rule
static Rule make_jump_rule(const std::string& chain) {
    Rule r;
    r.target.kind       = Target::Kind::kJump;
    r.target.jump_chain = chain;
    return r;
}

// Count rules in a given table/chain
static size_t rule_count(const RuleStore& store, TableKind table,
                          const std::string& chain) {
    const Chain* c = store.get_chain(table, chain);
    if (!c) return 0;
    return c->rules.size();
}

// ---------------------------------------------------------------------------
// 11.2 save() basic functionality
// ---------------------------------------------------------------------------

TEST(PersistSave, SaveEmptyStoreCreatesFile) {
    TempFile tmp;
    RuleStore store;
    bool ok = RulePersist::save(store, tmp.path);
    EXPECT_TRUE(ok);
    EXPECT_TRUE(fs::exists(tmp.path));
}

TEST(PersistSave, SavedFileContainsHeader) {
    TempFile tmp;
    RuleStore store;
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string first_line;
    std::getline(ifs, first_line);
    EXPECT_EQ(first_line, "# Generated by winiptables");
}

TEST(PersistSave, SavedFileContainsFilterTable) {
    TempFile tmp;
    RuleStore store;
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find("*filter"), std::string::npos);
    EXPECT_NE(content.find("COMMIT"),  std::string::npos);
}

TEST(PersistSave, SavedFileContainsChainPolicyLines) {
    TempFile tmp;
    RuleStore store;
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find(":INPUT ACCEPT [0:0]"),   std::string::npos);
    EXPECT_NE(content.find(":OUTPUT ACCEPT [0:0]"),  std::string::npos);
    EXPECT_NE(content.find(":FORWARD ACCEPT [0:0]"), std::string::npos);
}

TEST(PersistSave, SavedFileContainsRuleLines) {
    TempFile tmp;
    RuleStore store;
    store.append_rule(TableKind::kFilter, "INPUT", make_rule(Target::Kind::kDrop));
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find("-A INPUT -j DROP"), std::string::npos);
}

TEST(PersistSave, SaveDropPolicySerializedCorrectly) {
    TempFile tmp;
    RuleStore store;
    Target drop;
    drop.kind = Target::Kind::kDrop;
    store.set_policy(TableKind::kFilter, "FORWARD", drop);
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find(":FORWARD DROP [0:0]"), std::string::npos);
}

TEST(PersistSave, UserDefinedChainSerializedWithDashPolicy) {
    TempFile tmp;
    RuleStore store;
    store.create_chain(TableKind::kFilter, "MY_CHAIN");
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find(":MY_CHAIN - [0:0]"), std::string::npos);
}

TEST(PersistSave, JumpTargetSerializedCorrectly) {
    TempFile tmp;
    RuleStore store;
    store.create_chain(TableKind::kFilter, "MY_CHAIN");
    store.append_rule(TableKind::kFilter, "INPUT", make_jump_rule("MY_CHAIN"));
    RulePersist::save(store, tmp.path);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find("-A INPUT -j MY_CHAIN"), std::string::npos);
}

TEST(PersistSave, SaveToInvalidPathReturnsFalse) {
    RuleStore store;
    bool ok = RulePersist::save(store, "Z:\\nonexistent_dir\\rules.v4");
    EXPECT_FALSE(ok);
}

// ---------------------------------------------------------------------------
// 11.3 load() basic functionality
// ---------------------------------------------------------------------------

TEST(PersistLoad, LoadNonExistentFileReturnsFalse) {
    RuleStore store;
    bool ok = RulePersist::load(store, "Z:\\nonexistent\\rules.v4");
    EXPECT_FALSE(ok);
}

TEST(PersistLoad, LoadEmptyFileSucceeds) {
    TempFile tmp;
    { std::ofstream ofs(tmp.path); }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
}

TEST(PersistLoad, LoadCommentOnlyFileSucceeds) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "# Generated by winiptables\n";
        ofs << "# another comment\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
}

TEST(PersistLoad, LoadSetsChainPolicy) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT DROP [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD DROP [0:0]\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
    const Chain* input = store.get_chain(TableKind::kFilter, "INPUT");
    ASSERT_NE(input, nullptr);
    ASSERT_TRUE(input->policy.has_value());
    EXPECT_EQ(input->policy->kind, Target::Kind::kDrop);
}

TEST(PersistLoad, LoadAppendsRules) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD DROP [0:0]\n";
        ofs << "-A INPUT -j DROP\n";
        ofs << "-A INPUT -j ACCEPT\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
    EXPECT_EQ(rule_count(store, TableKind::kFilter, "INPUT"), 2u);
}

TEST(PersistLoad, LoadCreatesUserDefinedChain) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << ":MY_CHAIN - [0:0]\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
    EXPECT_NE(store.get_chain(TableKind::kFilter, "MY_CHAIN"), nullptr);
}

TEST(PersistLoad, LoadMultipleTables) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << "-A INPUT -j DROP\n";
        ofs << "COMMIT\n";
        ofs << "*nat\n";
        ofs << ":PREROUTING ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":POSTROUTING ACCEPT [0:0]\n";
        ofs << "-A POSTROUTING -j MASQUERADE\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_TRUE(ok);
    EXPECT_EQ(rule_count(store, TableKind::kFilter, "INPUT"),       1u);
    EXPECT_EQ(rule_count(store, TableKind::kNat,    "POSTROUTING"), 1u);
}

// ---------------------------------------------------------------------------
// 11.3 Syntax error handling
// ---------------------------------------------------------------------------

TEST(PersistLoad, UnknownTableReturnsError) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*badtable\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_FALSE(ok);
}

TEST(PersistLoad, RuleOutsideTableBlockReturnsError) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "-A INPUT -j DROP\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_FALSE(ok);
}

TEST(PersistLoad, RuleMissingJumpTargetReturnsError) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << "-A INPUT -p tcp\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_FALSE(ok);
}

TEST(PersistLoad, UnrecognizedLineReturnsError) {
    TempFile tmp;
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << "GARBAGE LINE\n";
        ofs << "COMMIT\n";
    }
    RuleStore store;
    bool ok = RulePersist::load(store, tmp.path);
    EXPECT_FALSE(ok);
}

// ---------------------------------------------------------------------------
// 11.4 --noflush mode
// ---------------------------------------------------------------------------

TEST(PersistNoFlush, DefaultFlushClearsExistingRules) {
    TempFile tmp;
    RuleStore store;
    store.append_rule(TableKind::kFilter, "INPUT", make_rule(Target::Kind::kDrop));
    ASSERT_EQ(rule_count(store, TableKind::kFilter, "INPUT"), 1u);
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << "COMMIT\n";
    }
    bool ok = RulePersist::load(store, tmp.path, false);
    EXPECT_TRUE(ok);
    EXPECT_EQ(rule_count(store, TableKind::kFilter, "INPUT"), 0u);
}

TEST(PersistNoFlush, NoFlushPreservesExistingRules) {
    TempFile tmp;
    RuleStore store;
    store.append_rule(TableKind::kFilter, "INPUT", make_rule(Target::Kind::kDrop));
    ASSERT_EQ(rule_count(store, TableKind::kFilter, "INPUT"), 1u);
    {
        std::ofstream ofs(tmp.path);
        ofs << "*filter\n";
        ofs << ":INPUT ACCEPT [0:0]\n";
        ofs << ":OUTPUT ACCEPT [0:0]\n";
        ofs << ":FORWARD ACCEPT [0:0]\n";
        ofs << "-A INPUT -j ACCEPT\n";
        ofs << "COMMIT\n";
    }
    bool ok = RulePersist::load(store, tmp.path, true);
    EXPECT_TRUE(ok);
    EXPECT_EQ(rule_count(store, TableKind::kFilter, "INPUT"), 2u);
}

// ---------------------------------------------------------------------------
// Property 1: Round-Trip property
// **Validates: Requirements 1.1** (rule persistence round-trip property)
// ---------------------------------------------------------------------------

TEST(PersistRoundTrip, EmptyStoreRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    for (const char* chain : {"INPUT", "OUTPUT", "FORWARD"}) {
        const Chain* c1 = store1.get_chain(TableKind::kFilter, chain);
        const Chain* c2 = store2.get_chain(TableKind::kFilter, chain);
        ASSERT_NE(c1, nullptr);
        ASSERT_NE(c2, nullptr);
        ASSERT_TRUE(c1->policy.has_value());
        ASSERT_TRUE(c2->policy.has_value());
        EXPECT_EQ(c1->policy->kind, c2->policy->kind)
            << "Policy mismatch for chain " << chain;
    }
}

TEST(PersistRoundTrip, RulesPreservedAfterRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    store1.append_rule(TableKind::kFilter, "INPUT",   make_rule(Target::Kind::kDrop));
    store1.append_rule(TableKind::kFilter, "INPUT",   make_rule(Target::Kind::kAccept));
    store1.append_rule(TableKind::kFilter, "FORWARD", make_rule(Target::Kind::kDrop));
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "INPUT"),   2u);
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "FORWARD"), 1u);
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "OUTPUT"),  0u);
}

TEST(PersistRoundTrip, PolicyDropPreservedAfterRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    Target drop;
    drop.kind = Target::Kind::kDrop;
    store1.set_policy(TableKind::kFilter, "FORWARD", drop);
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    const Chain* fwd = store2.get_chain(TableKind::kFilter, "FORWARD");
    ASSERT_NE(fwd, nullptr);
    ASSERT_TRUE(fwd->policy.has_value());
    EXPECT_EQ(fwd->policy->kind, Target::Kind::kDrop);
}

TEST(PersistRoundTrip, UserDefinedChainPreservedAfterRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    store1.create_chain(TableKind::kFilter, "MY_CHAIN");
    store1.append_rule(TableKind::kFilter, "INPUT", make_jump_rule("MY_CHAIN"));
    store1.append_rule(TableKind::kFilter, "MY_CHAIN", make_rule(Target::Kind::kDrop));
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    EXPECT_NE(store2.get_chain(TableKind::kFilter, "MY_CHAIN"), nullptr);
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "INPUT"),    1u);
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "MY_CHAIN"), 1u);
}

TEST(PersistRoundTrip, MultiTableRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    store1.append_rule(TableKind::kFilter, "INPUT",       make_rule(Target::Kind::kDrop));
    store1.append_rule(TableKind::kNat,    "POSTROUTING", make_rule(Target::Kind::kMasquerade));
    store1.append_rule(TableKind::kMangle, "PREROUTING",  make_rule(Target::Kind::kAccept));
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    EXPECT_EQ(rule_count(store2, TableKind::kFilter, "INPUT"),       1u);
    EXPECT_EQ(rule_count(store2, TableKind::kNat,    "POSTROUTING"), 1u);
    EXPECT_EQ(rule_count(store2, TableKind::kMangle, "PREROUTING"),  1u);
}

TEST(PersistRoundTrip, RuleTargetKindPreservedAfterRoundTrip) {
    TempFile tmp;
    RuleStore store1;
    store1.append_rule(TableKind::kFilter, "INPUT",   make_rule(Target::Kind::kDrop));
    store1.append_rule(TableKind::kFilter, "OUTPUT",  make_rule(Target::Kind::kAccept));
    store1.append_rule(TableKind::kFilter, "FORWARD", make_rule(Target::Kind::kReturn));
    ASSERT_TRUE(RulePersist::save(store1, tmp.path));
    RuleStore store2;
    ASSERT_TRUE(RulePersist::load(store2, tmp.path));
    auto get_first_target = [&](TableKind t, const std::string& chain) {
        const Chain* c = store2.get_chain(t, chain);
        if (!c || c->rules.empty()) return Target::Kind::kAccept;
        return c->rules.front()->target.kind;
    };
    EXPECT_EQ(get_first_target(TableKind::kFilter, "INPUT"),   Target::Kind::kDrop);
    EXPECT_EQ(get_first_target(TableKind::kFilter, "OUTPUT"),  Target::Kind::kAccept);
    EXPECT_EQ(get_first_target(TableKind::kFilter, "FORWARD"), Target::Kind::kReturn);
}

// ---------------------------------------------------------------------------
// 11.5 Async write
// ---------------------------------------------------------------------------

TEST(PersistAsync, SaveAsyncReturnsValidFuture) {
    TempFile tmp;
    RuleStore store;
    auto fut = RulePersist::save_async(store, tmp.path);
    EXPECT_TRUE(fut.valid());
    bool ok = fut.get();
    EXPECT_TRUE(ok);
    EXPECT_TRUE(fs::exists(tmp.path));
}

TEST(PersistAsync, SaveAsyncWritesCorrectContent) {
    TempFile tmp;
    RuleStore store;
    store.append_rule(TableKind::kFilter, "INPUT", make_rule(Target::Kind::kDrop));
    auto fut = RulePersist::save_async(store, tmp.path);
    bool ok = fut.get();
    EXPECT_TRUE(ok);
    std::ifstream ifs(tmp.path);
    std::string content((std::istreambuf_iterator<char>(ifs)),
                         std::istreambuf_iterator<char>());
    EXPECT_NE(content.find("-A INPUT -j DROP"), std::string::npos);
}

TEST(PersistAsync, SaveAsyncDoesNotBlockCaller) {
    TempFile tmp;
    RuleStore store;
    auto start = std::chrono::steady_clock::now();
    auto fut = RulePersist::save_async(store, tmp.path);
    auto elapsed = std::chrono::steady_clock::now() - start;
    EXPECT_LT(std::chrono::duration_cast<std::chrono::milliseconds>(elapsed).count(),
              500);
    fut.get();
}
